# Generated by Django 2.0.7 on 2020-03-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(choices=[('WTR', 'Winter'), ('SMR', 'Summer'), ('FL', 'Fall'), ('SPR', 'Spring')], default='WTR', max_length=3)),
                ('season_desc', models.CharField(default='season description in few lines', max_length=200)),
            ],
        ),
    ]
